---
title: "hunting"
author: "Jackson Coldiron and Kaitlin Castor"
editor: visual
format: 
  html:
    code-fold: true
    embed-resources: true
    theme: sandstone
    toc: false
execute:
  freeze: auto 
  warning: false
  message: false
---

## Model Implementation

### Import libraries

```{r}
# Load required libraries
library(sensitivity)
library(tidyverse)
library(deSolve)
library(here)
```

### Prepare function

```{r}
#import function
source(here("R","lotvmodH.R"))

#add paramters
pars <- c(rprey = 0.95, alpha = 0.01, eff = 0.6, pmort = 0.4, k = 2000)

#population stability = when predator and prey derivitives equal zero
```

## Model Exploration

### different hunting rates

```{r}

```

### different minimum prey populations

```{r}
#look at different minimum prey populations (before hunting is allowed) --> how does it effect stability of both populations?

#add pars
pars <- c(hunt = 0.03 , rprey = 0.95, alpha = 0.01, eff = 0.6, pmort = 0.4, k = 2000)

#current population
pop <- c(prey = 75, pred = 55)

#maintaining a population 50 years into the future
days = seq(from=1,to=18250) 

#testing derivative over a range of minimum prey populations
minprey = seq(from = 1, to = 50, by = 1)
findstable <- data.frame(minprey)

findstable$lotvmodH <- unlist(findstable$minprey %>% map(~ lotvmodH(t = days, pop = pop, pars = pars)))

ggplot(findstable, aes(minprey, dprey)) +
  geom_point() +
  geom_hline(yintercept = 0, col = "red") +
  labs(y = "Derivative\n (Rate of change of prey population) (# of prey/time)", x = "Minimum prey population (# of prey)")

# look at a different hunting rates
midHrate <- 0.02
parms <- list(hunt = midHrate, rprey = 0.95, alpha = 0.01, eff = 0.6, pmort = 0.4, k = 2000)
findstable$lotvmodH <- unlist(findstable$minprey %>% map(~ lotvmodH(t = days, pop = pop, pars = parms)))
highHrate <- 0.05
parms <- list(hunt = highHrate, rprey = 0.95, alpha = 0.01, eff = 0.6, pmort = 0.4, k = 2000)
findstable$lotvmodH <- unlist(findstable$minprey %>% map(~ lotvmodH(t = days, pop = pop, pars = parms)))


```

## Model Stability Explanation
